#!/usr/bin/env sh

set -xe

dir="$HOME/Backup/$(date +%Y)/$(date +%m)-$(date +%d)"
folders="$HOME/Dotfiles $HOME/Downloads $HOME/Pictures $HOME/Projects $HOME/Text"

mkdir -p $dir

if ! xset -q &> /dev/null
then
    echo "do_backup: Starting backup (stored at $dir)"
else
    notify-send "do_backup: Starting backup (stored at $dir)"
fi

for name in $folders
do
  out_name=$dir/$(basename $name).tar.xz
  XZ_OPT='-T0 -9' tar -Jcvf $out_name -C $name .
done

if ! xset -q &> /dev/null
then
    echo "do_backup: Finished backup"
else
    notify-send "do_backup: Finished backup"
fi
