#!/bin/sh
P=$HOME
sudo xboxdrv --silent \
     -c $P/.config/xboxdrv/general.xboxdrv \
     --alt-config $P/.config/xboxdrv/typing.xboxdrv \
     --alt-config $P/.config/xboxdrv/media.xboxdrv \
     --axis-sensitivity X1=-1.0,X2=-1.0,Y1=-1.0,Y2=-1.0
