#!/usr/bin/env sh

sudo xboxdrv --silent \
     -c $HOME/.config/xboxdrv/general.xboxdrv \
     --alt-config $HOME/.config/xboxdrv/typing.xboxdrv \
     --alt-config $HOME/.config/xboxdrv/media.xboxdrv \
     --axis-sensitivity X1=-1.0,X2=-1.0,Y1=-1.0,Y2=-1.0
