#!/usr/bin/env bash
set -euo pipefail

# lock_image=$HOME/Pictures/Lockscreens/0062.png
lock_image="$HOME/Pictures/Lockscreens/$(ls $HOME/Pictures/Lockscreens | shuf | head -1)"
i3lock -nbfe -i $lock_image -c 000000 # 33ee88
