#!/usr/bin/env bash
set -euo pipefail

# lock_image=$HOME/Pictures/Lockscreens/0062.png
XSECURELOCK_PAM_SERVICE=xsecurelock \
    XSECURELOCK_SAVER=saver_xscreensaver \
    XSECURELOCK_PASSWORD_PROMPT=time_hex \
    xsecurelock
