#!/bin/bash

delimiter=' | '

timedate() {
    echo $(date +'%a %F %R')
}

battery() {
	capacity=$(cat /sys/class/power_supply/BAT0/capacity) || break
	status=$(cat /sys/class/power_supply/BAT0/status)

    if [[ $status == "Charging" ]]
    then
        status=""
    else
        if [[ $capacity -ge 75 ]]
        then
            status=""
        elif [[ $capacity -ge 50 ]]
        then
            status=""
        elif [[ $capacity -ge 25 ]]
        then
            status=""
        elif [[ $capacity -ge 10 ]]
        then
            status=""
        else
            status=""
        fi
    fi
    echo "$status  $capacity%"
}

volume() {
    sinks="$(pactl list sinks)"
    vol="$(echo "$sinks" | grep '[0-9]\+%' | sed "s,.* \([0-9]\+\)%.*,\1,;1q")"

    if [[ $vol -gt 50 ]]
    then
        icon=""
    elif [[ $vol -gt 10 ]]
    then
         icon=""
    else
        icon=""
    fi

    echo "$icon $vol%"
}

ram() {
    echo $(vmstat -s -a -S M | grep 'used memory' | grep -Po "\d+")M
}

disk() {
    echo $(df | grep /dev/sda2 | awk '{print $5}')
}

while true; do
    xsetroot -name "Meme level at $(disk) $delimiter $(ram) $delimiter $(volume) $delimiter $(battery) $delimiter $(timedate)"
    sleep 30s;
done
