#!/usr/bin/env sh

processes="st btop
emacsclient -c -a emacs
$HOME/.local/scripts/browser
steam
discord
spotify"


printf '%s\n' "$processes" | \
    while IFS= read -r proc; do
        $proc & disown
    done
