#+TITLE: Dotfiles
#+AUTHOR: Aryadev Chavali
#+DESCRIPTION: README for Dotfiles

This repository contains all of my custom configurations for programs
I use daily.

* Setup and installation procedure
1) Clone this repository to =~/Dotfiles=
2) Construct the following directories:
   + =~/.local=
     + =src=
     + =bin=
     + =lib=
     + =share=
   + =~/.config=
   + =~/Downloads=
   + =~/Code=
   + =~/Media=
   + =~/Projects=
3) Install [[https://www.gnu.org/software/stow/][GNU/stow]]
4) Pick and choose what configurations you want
   + To install a module use ~stow <module>~
   + To remove a module use ~stow -D <module>~
* Installing Emacs
I like a specific set of flags on my Emacs install, and my
configuration kind of depends on them existing as well.  Prepackaged
installs just won't cut it.  So I'd highly recommend cloning and
building my personal
[[https://github.com/oreodave/emacs-29-custom][Emacs repo]] (currently
=v29=).

Or just run the following lines:

#+begin_src sh
cd ~/.local/src;
git clone git@github.com:oreodave/emacs-29-custom emacs;
cd emacs;
sh personal-install; # Will configure, build and attempt to install
#+end_src
* Emacs archives
At [[https://aryadevchavali.com/resources/]] I want a kind of updated
version of my configuration which contains most of my Emacs
configuration.  This is so I can quick start on most machines without
having to pull the repositories for packages first, just spend time
building bytecode.

This script generates the archive:
#+begin_src sh
tar -Jcvf emacs-config.tar.xz \
    ~/.config/emacs/app.org \
    ~/.config/emacs/config.org \
    ~/.config/emacs/core.org \
    ~/.config/emacs/lang.org \
    ~/.config/emacs/early-init.el \
    ~/.config/emacs/init.el \
    ~/.config/emacs/elisp/ \
    ~/.config/emacs/straight
#+end_src

And this script sends it over via rsync
#+begin_src sh
rsync -avz --info=progress2 --info=name0 emacs-config.tar.xz root@aryadevchavali.com:/var/www/html/resources
#+end_src
