#!/bin/sh

# unread;inbox;warwick;banks;receipts;spotify
notmuch tag +inbox +unread -new -- tag:new

notmuch tag -new -unread -inbox +sent from:"aryadev@aryadevchavali.com"
notmuch tag -inbox -unread +spam \
        path:'general/Junk/**'

notmuch tag -inbox +warwick from:'*@warwick.ac.uk*'
notmuch tag -inbox +receipts \
        from:'*@paypal.co.uk*' \
        from:'*@namcheap.com*' \
        from:'*@digitalocean.com*' \
        from:'*@spotify.com*' \
        from:'*@nationalexpress.com*' \
        from:'o2shop@s-email-o2.co.uk' \
        from:'*@billing.o2.com'

notmuch tag -inbox +jobs \
        from:'*@jobs*' \
        from:'*@indeed.com*' \
        from:'*@linkedin.com' \
        from:'*@thecareerwallet*' \
        from:'*@cv-library.co.uk' \
        from:'*@pertemps.co.uk' \
        from:'*@joinrs.com' \
        from:'*@careeralert.co.uk'

notmuch tag -inbox +social \
        from:'no-reply@twitch.tv'


notmuch tag -inbox +bank from:'*@*hsbc*' from:'*@*lloydsbank*'

notmuch tag +flagged from:'expiry@letsencrypt.org'

notmuch tag -inbox +unread +trading from:"*trading212.com"
