#!/bin/sh

bspc monitor -d "Development" "Browser" "Media" "4"

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled

launch_polybar &
bspwm
