(deftheme personal-primary
  "Created 2021-10-20.")

(custom-theme-set-faces
 'personal-primary
 '(button ((t (:inherit (link)))))
 '(tab-bar ((t (:background "grey13"))))
 '(tab-bar-tab ((t (:background "grey20" :foreground "white" :box (:color )))))
 '(tab-bar-tab-inactive ((t (:background "grey13" :foreground "DimGrey"))))
 '(child-frame-border ((t (:background "white"))))
 '(company-preview
   ((t (:foreground "wheat" :background "blue4"))))
 '(company-preview-common ((t (:inherit company-preview :foreground "grey"))))
 '(company-tooltip ((t (:background "black" :foreground "white"))))
 '(company-tooltip-annotation ((t (:foreground "grey" :slant italic))))
 '(company-tooltip-selection ((t (:background "grey31" :slant italic))))
 '(cursor ((t (:background "white"))))
 '(dired-ignored ((t (:background "grey10" :slant italic :underline t))))
 '(escape-glyph ((t (:foreground "cyan"))))
 '(eshell-ls-directory ((t (:foreground "DeepSkyBlue3" :weight bold))))
 '(eshell-prompt ((t (:foreground "turquoise3" :weight bold))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(font-lock-builtin-face ((t (:foreground "powder blue"))))
 '(font-lock-comment-delimiter-face ((t (:slant italic :foreground "grey24"))))
 '(font-lock-comment-face ((t (:slant italic :foreground "#868686"))))
 '(font-lock-constant-face ((t (:foreground "indian red" :weight semi-bold :height 0.99 :family "Source Code Pro"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:weight semi-bold :foreground "#b6b6b6"))))
 '(font-lock-function-call-face ((t (:weight semi-bold :foreground "#b6b6b6"))))
 '(font-lock-keyword-face ((t (:foreground "spring green" :weight bold :height 0.95 :family "Fira Code"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:family "Source Code Pro" :foreground "#868686"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:family "DejaVu Sans Mono" :slant italic :weight light :foreground "yellow4"))))
 '(font-lock-type-face ((t (:weight light :foreground "deepskyblue" :family "DejaVu Sans Mono"))))
 '(font-lock-variable-name-face ((nil (:family "Source Code Pro" :foreground "white"))))
 '(font-lock-warning-face ((t (:inherit (error)))))
 '(fringe ((t (:background "grey4"))))
 '(haskell-interactive-face-prompt ((t (:foreground "green"))))
 '(header-line ((t (:box nil :foreground "grey90" :background "grey20" :inherit (mode-line)))))
 '(highlight ((t (:extend t :background "#222233"))))
 '(homoglyph ((t (:foreground "cyan"))))
 '(isearch ((t (:foreground "brown4" :background "white"))))
 '(isearch-fail ((t (:background "red4"))))
 '(ivy-current-match ((t (:weight bold :underline t :slant italic))))
 '(lazy-highlight ((t (:background "paleturquoise4"))))
 '(line-number ((t (:foreground "grey45" :background "grey1" :inherit (default)))))
 '(line-number-current-line ((t (:foreground "white" :background "grey1" :inherit (default)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "cyan1"))))
 '(link-visited ((t (:foreground "violet" :inherit (link)))))
 '(match ((t (:background "RoyalBlue3"))))
 '(minibuffer-prompt ((t (:foreground "cyan"))))
 '(mode-line ((t (:box nil :foreground "LightSkyBlue" :background "black"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-inactive ((t (:weight light :foreground "CadetBlue" :background "grey7"
                           :inherit (mode-line)))))
 '(next-error ((t (:inherit (region)))))
 '(orderless-match-face-0 ((t (:weight bold :foreground "lime green"))))
 '(orderless-match-face-1 ((t (:weight bold :foreground "light green"))))
 '(orderless-match-face-2 ((t (:weight bold :foreground "forest green"))))
 '(orderless-match-face-3 ((t (:weight bold :foreground "dark green"))))
 '(org-block ((t (:background "grey3" :inherit shadow))))
 '(org-code ((t (:foreground "green3"))))
 '(org-quote ((t (:slant italic))))
 '(org-verbatim ((t (:foreground "red3"))))
 '(pdf-isearch-batch ((t (:foreground "black" :background "white"))))
 '(query-replace ((t (:inherit (isearch)))))
 '(region ((t (:extend t :background "grey25"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50"))
           (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70"))
           (((class color) (min-colors 8) (background light)) (:foreground "green"))
           (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection
   ((t (:extend t :background "SkyBlue4"))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1"))
                        (((class color) (background dark)) (:background "red1"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(whitespace-line ((t (:background "black" :foreground "violet"))))
 '(whitespace-space ((t (:background "grey6" :foreground "black"))))
 '(whitespace-tab ((t (:background "grey5" :foreground "grey20"))))
 '(default ((t (:family "Source Code Pro" :foundry "ADBO" :width normal
                :weight normal :slant normal :underline nil :overline nil
                :extend nil :strike-through nil :box nil :inverse-video nil
                :foreground "#b6b6b6" :background "black" :stipple nil :inherit nil)))))

(provide-theme 'personal-primary)
