#!/usr/bin/env bash
capacity=$(cat /sys/class/power_supply/BAT0/capacity) || break
time_left=$($HOME/.local/scripts/status/battery_time_left);
status=$(cat /sys/class/power_supply/BAT0/status)

if [[ $status == "Charging" ]]
then
    status=""
else
    if [[ $capacity -ge 75 ]]
    then
        status=""
    elif [[ $capacity -ge 50 ]]
    then
        status=""
    elif [[ $capacity -ge 25 ]]
    then
        status=""
    elif [[ $capacity -ge 10 ]]
    then
        status=""
    else
        notify-send -u critical "Charge now!"
        status=""
    fi
fi
echo "$status $capacity% $time_left"
