#!/bin/bash

while :
do
  prev="$(playerctl --player=spotify metadata title)"
  while [[ $item == $prev ]]
  do
    sleep 1;
    item="$(playerctl --player=spotify metadata title)";
  done
  kill -48 $(pidof dwmblocks);
  item="";
done
