(deftheme derivative-new-molokai
  "Created 2020-07-19.")

(custom-theme-set-faces
 'derivative-new-molokai
 '(cursor ((t (:background "#F92660"))))
 '(fixed-pitch ((t (:family "Source Code Pro" :foundry "ADBO" :width normal :height 113 :weight normal :slant normal))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#FD971F"))))
 '(highlight ((t (:background "#333333"))))
 '(region ((t (:extend t :background "dim gray"))))
 '(shadow ((t (:foreground "#555556"))))
 '(secondary-selection ((t (:extend t :background "#525254"))))
 '(trailing-whitespace ((t (:background "red"))))
 '(font-lock-builtin-face ((t (:foreground "#FD971F"))))
 '(font-lock-comment-delimiter-face ((t (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:slant normal :foreground "#555556"))))
 '(font-lock-constant-face ((t (:foreground "#FFFFFFF"))))
 '(font-lock-doc-face ((t (:slant normal :foreground "#7f7f80"))))
 '(font-lock-function-name-face ((t (:foreground "#A6E22E"))))
 '(font-lock-keyword-face ((t (:foreground "#F92660"))))
 '(font-lock-negation-char-face ((t (:foreground "#F92660" :inherit (bold)))))
 '(font-lock-preprocessor-face ((t (:foreground "#F92660" :inherit (bold)))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#F92660" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#F92660" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#E6DB74"))))
 '(font-lock-type-face ((t (:slant normal :foreground "#66D9EF"))))
 '(font-lock-variable-name-face ((t (:foreground "#F8F8F2"))))
 '(font-lock-warning-face ((t (:inherit (warning)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#FD971F"))))
 '(link-visited ((t (:foreground "violet" :inherit (link)))))
 '(fringe ((t (:foreground "#4E4E4E" :inherit (default)))))
 '(header-line ((t (:foreground "#F8F8F2" :background "#272822"))))
 '(tooltip ((t (:foreground "#F8F8F2" :background "#2D2E2E"))))
 '(mode-line ((t (:box nil :background "#161613"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#FD971F"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box nil :foreground "#4E4E4E" :background "#171819"))))
 '(isearch ((t (:foreground "#1B2229" :background "#A6E22E"))))
 '(isearch-fail ((t (:weight bold :foreground "#1B2229" :background "#E74C3C"))))
 '(lazy-highlight ((t (:weight bold :foreground "#1B2229" :background "#9C91E4"))))
 '(match ((t (:weight bold :foreground "#A6E22E" :background "#1B2229"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(company-tooltip-selection ((t (:background "blue"))))
 '(company-tooltip-annotation ((t (:foreground "deep sky blue"))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "black" :foreground "#F8F8F2" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 113 :width normal :foundry "ADBO" :family "Source Code Pro"))))
 '(company-box-background ((t (:inherit company-tooltip))))
 '(company-tooltip ((t (:background "dim gray" :foreground "white")))))

(provide-theme 'derivative-new-molokai)
